services:
  metube:
    build: .
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies
      - ./robots.txt:/robots.txt
      - ./ui/dist:/metube/ui/dist
    environment:
      - 'OUTPUT_TEMPLATE=%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S.%(ext)s'
      - 'YTDL_OPTIONS={"format": "best", "exec": "ffmpeg -i %(filepath)q -c:v libx264 -c:a aac %(filepath)q.h264.mp4", "cookiefile":"/cookies/cookies.txt"}'
      - DELETE_FILE_ON_TRASHCAN=true
      - DOWNLOAD_MODE=limited
      - MAX_CONCURRENT_DOWNLOADS=10
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/downloads/audio
      - USE_USER_ISOLATION=true
      - UID=1000
      - GID=1000
      - CREATE_CUSTOM_DIRS=true
      - HTTPS=true
      - CERTFILE=/ssl/crt.pem
      - KEYFILE=/ssl/key.pem